apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-cron
spec:
  template:
    spec:
      containers:
        - name: cron
          image: retracedhq/retraced:1.5.3
          imagePullPolicy: IfNotPresent
