apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-dbutil
spec:
  template:
    spec:
      containers:
        - name: dbutil
          image: retracedhq/retraced:1.5.3
          imagePullPolicy: IfNotPresent
