apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-admin-portal
spec:
  template:
    spec:
      containers:
        - name: admin-portal
          image: boxyhq/jackson:1.7.1
          ports:
            - containerPort: 5225
