apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-api
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: bootstrap
          image: retracedhq/retraced-local
          command:
            - /bin/sh
          args:
            - -c
            - ./build/src/retracedctl
              bootstrap
              --projectName   "$BOOTSTRAP_PROJECT_NAME"
              --projectId     "$BOOTSTRAP_PROJECT_ID"
              --environmentId "$BOOTSTRAP_ENVIRONMENT_ID"
              --apiKey        "$BOOTSTRAP_API_TOKEN"
          envFrom:
            - secretRef:
                name: auditlog
          env:
            - name: BOOTSTRAP_PROJECT_NAME
              value: dev
            - name: BOOTSTRAP_PROJECT_ID
              value: dev
            - name: BOOTSTRAP_ENVIRONMENT_ID
              value: dev
            - name: BOOTSTRAP_API_TOKEN
              value: dev
      containers:
        - name: api
          readinessProbe:
            httpGet:
              port: 3000
              path: /healthz
          command:
            - node
            - --inspect=0.0.0.0
            - build/src/index.js
          ports:
            - containerPort: 9229
          env:
            - name: EXPORT_PAGE_SIZE_INTERNAL
              value: "2"
