apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackson-admin-portal
spec:
  template:
    spec:
      containers:
        - name: jackson
          image: boxyhq/jackson:1.6.0
          ports:
            - containerPort: 5225
          env:
            - name: DB_URL
              value: "postgres://retraced:password@retraced-postgres:5432/postgres"
            - name: SAML_AUDIENCE
              value: ""
            - name: JACKSON_API_KEYS
              value: ""
            - name: DB_TYPE
              value: ""
            - name: DB_TTL
              value: ""
            - name: DB_CLEANUP_LIMIT
              value: ""
            - name: DB_ENCRYPTION_KEY
              value: ""
            - name: SMTP_HOST
              value: ""
            - name: SMTP_PORT
              value: ""
            - name: SMTP_USER
              value: ""
            - name: SMTP_PASSWORD
              value: ""
            - name: SMTP_FROM
              value: ""
            - name: NEXTAUTH_JWT_SIGNING_PRIVATE_KEY
              value: ""
            - name: NEXTAUTH_URL
              value: "http://localhost:5225"
            - name: NEXTAUTH_SECRET
              value: ""
            - name: NEXTAUTH_ACL
              value: ""
            - name: RETRACED_HOST_URL
              value: "http://retraced-api:3000/auditlog"
            - name: RETRACED_EXTERNAL_URL
              value: "http://localhost:3000/auditlog"
            - name: RETRACED_ADMIN_ROOT_TOKEN
              value: "dev"
            - name: BOXYHQ_LICENSE_KEY
              value: ""
