resources:
- ./api-deployment.yaml
- ./api-service.yaml
- ./cron-deployment.yaml
- ./dbutil-deployment.yaml
- ./migratees-job.yaml
- ./migratepg-job.yaml
- ./nsqd-deployment.yaml
- ./nsqd-service.yaml
- ./processor-deployment.yaml
namespace: default
