apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      - name: bootstrap
        image: registry.replicated.com/shipretraced/retraced:1.3.35
        command:
        - /bin/sh
        args:
        - -c
        - node -r ts-node/register src/retracedctl.ts
            bootstrap
            --projectName   "$BOOTSTRAP_PROJECT_NAME"
            --projectId     "$BOOTSTRAP_PROJECT_ID"
            --environmentId "$BOOTSTRAP_ENVIRONMENT_ID"
            --apiKey        "$BOOTSTRAP_API_TOKEN"
        envFrom:
          - secretRef:
              name: auditlog
        env:
        - name: BOOTSTRAP_PROJECT_NAME
          value: dev
        - name: BOOTSTRAP_PROJECT_ID
          value: dev
        - name: BOOTSTRAP_ENVIRONMENT_ID
          value: dev
        - name: BOOTSTRAP_API_TOKEN
          value: dev
      containers:
        - name: api
          readinessProbe:
            httpGet:
              port: 3000
              path: /healthz
          command:
            - node
            - --inspect=0.0.0.0
            - -r
            - ts-node/register
            - src/index.ts
          ports:
          - containerPort: 9229
          env:
          - name: EXPORT_PAGE_SIZE_INTERNAL
            value: "2"
